version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/postgresql/data 

# ----- Use this for storing in local driver -----
#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local